# Generated by Django 2.2.4 on 2019-08-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190826_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение автора'),
        ),
    ]
