# Generated by Django 2.2.4 on 2019-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Выберите изображение автора', null=True, upload_to='authors', verbose_name='Изображение автора'),
        ),
    ]
