# Generated by Django 2.2.4 on 2019-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190830_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
