# Generated by Django 2.2.4 on 2019-08-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='book_file',
        ),
    ]
