# Generated by Django 2.2.4 on 2019-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190830_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_file',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, default=None, help_text='Добавьте файл', null=True, upload_to='', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Добавьте изображение книги', null=True, upload_to='', verbose_name='Изображение книги'),
        ),
    ]
