# Generated by Django 2.2.4 on 2019-09-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190830_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображение png/jpg', null=True, upload_to='users', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Добавьте изображение книги', null=True, upload_to='books', verbose_name='Изображение книги'),
        ),
    ]
